### ISSUE TITLE
First database version

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#1]
After discussion with @Starcounter-Jack we decided to use [Society-Objects](https://github.com/StarcounterSamples/Society-Objects) instead of [Simplified](https://github.com/StarcounterSamples/Simplified) because it is too simplified.

Some changes to terminology:
- Warehouse - Starcounter hive
- AppStore - Vendor hive

Database for both of the sides should be the same. The database classes should be highly normalised and in `Concepts.Ring8` namespace.

Here is a code snippet for the very first classes:

```cs
var company = new Company() {
    Name = "Tunity"
};

var vendor = new Vendor() {
    WhoIs = company
};

var appStore = new AppStore() {
    Name = "Tunity app store",
    Vendor = vendor // ?? Should it be here?
};

var app = new App() {
    Name = "Tunity CRM"
};

var appInStore = new AppInStore() {
    WhoIs = app,
    ToWhom = appStore
};
```

The first version of database should contain all of those classes:
![image](https://cloud.githubusercontent.com/assets/6435556/12552514/9c5acc10-c372-11e5-9c60-7f652e92f618.png)

@Starcounter-Jack might be able to prepare complete code snippet as above for the entire database model.

**Comment by andwah** [comment]
> Warehouse - Starcounter hive
> AppStore - Vendor hive

Im a bit confused, is "Starcounter hive" both the place where Apps is managed (Old AppStoreServer) AND where we can host customer's hives?, i think they should be two different entities. and have different names.

**Comment by andwah** [comment]
@Starcounter-Jack Have you decided if you are doing the code snippets? i want to avoid  to start and then rewrite my code to match your code.

**Comment by miyconst** [comment]
@andwah you are right, those two are not the same. The place where we host customer hives (vendor hives) is just a hosting machine. Starcounter hive is the central place or Warehouse for all the stores and apps.

This terminology was proposed by @Starcounter-Jack.

**Comment by andwah** [comment]
So "Starcounter hive" and "Vendor hive" is two totally different things. 
Anyway we can change the naming later if we come up with something better :-)

**Comment by miyconst** [comment]
Yes, two totally different things. And the name is also a big confusing for me. I prefer Warehouse and AppStoreClient.

**Comment by miyconst** [comment]
After long meeting with @Starcounter-Jack and @warpech it was decided that we create our own Warehouse database inside the application.

Required classes such as `SystemUser` and `Organization` will be mapped to Simplified, which is mapped to SocietyObjects.

Warehouse app can reference `Simplified.dll` to access to `SystemUser` helper methods.

I have created a new clean branch of Warehouse, it has first, but not yet complete, version of the private database. The database and future changes are confirmed by @Starcounter-Jack.

**Comment by per-samuelsson** [comment]
Would it be possible to make even a higher level design / concept scheme of all this, now that it seem to grow? For me, that is not involved really, its quite hard to see the bigger picture. Yet I find myself sometime having to describe it to our users.

I *think* I understand how some of the things relate, and if that's correct, I'm with the camp that think the "hive" terminology is worse than the other proposals. And especially so if hive can mean two totally different things in two different contexts (yet relating to the same bigger architecture).

**Comment by miyconst** [comment]
@per-samuelsson don't worry. We didn't not stick with none of those tricky words.

Right now we have to major names:

Warehouse - Starcounter host for every Customer and his apps.
App Depot - Client side website which displays list of apps of a certain depot (previously store) of certain customer to their clients.

**Comment by miyconst** [comment]
I am closing this issue as the database is defined and confirmed.
