### ISSUE TITLE
Wrong namespaces in Prefabs

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Warehouse#103]
I've just tried to upload UserAdmin to StarcounterPrefabs in new Warehouse. I got an error: `UserAdmin-4.0.3-pnext.zip, Uploaded version namespace (StarcounterPrefabs.UserAdmin) does not match application namespace (StarcounterSamples.UserAdmin)`. 
Then I found out that all of our Prefabs in new warehouse have wrong namespace.

* How the namespace is resolved by `starpack`?
* Is it possible to change the namespace directly at warehouse?
* Is it a mistake made on first version upload?

My point is that in all Prefabs apps we should have StarcounterPrefabs namespace instead of StarcounterSamples. 

cc @andwah

**Comment by Mnosek** [comment]
also cc @Joltrix

**Comment by Joltrix** [comment]
Yeah, I noticed this as well, I noticed that we can change it manually though, so I guess that is a temporary solution. But changing the namespace inside the package.config file can make them "stack"

In the new warehouse, all the apps are clustered, for example: the Launcher (in the new warehouse). It displays all the previous versions as it is clicked.

When an app is uploaded, it does not conform to that pattern, But by changing the namespace to whatever the other launcher versions have, they "stack"

**Comment by andwah** [comment]
I changed the namespace from `StarcounterSamples` to `StarcounterPrefabs`.  In Warehouse we need to upload the new version to the Organization and not to the 'old' application. This will result in two applications with the same name but different namespaces. then if possible i recommend to delete to old application with the `StarcounterSamples` namespace.

> How the namespace is resolved by starpack?

It uses the actual executable namespace of the executable (assembly) + the assembly name.

> Is it possible to change the namespace directly at warehouse?

No

But It can be overridden by adding this line to `assemblyinfo.cs` in your application.

`[assembly: AssemblyMetadata("ID", "organization.myappname")]
`
> Is it a mistake made on first version upload?

Yes.

**Comment by mmnosek** [comment]
Thanks for answers! It has clarified a lot. 
I just had a discussion with @warpech about namespaces. The problem is, that sometimes we promote StarcounterSamples to StarcounterPrefabs when we decide that app is "more production ready". It will generate exactly the same problem.

We decided to change all namespaces in our apps to `Starcounter.AppName`. We don't have the same apps in different organizations anyway. I just want to confirm that it won't generate any problems. Could you confirm? :)

**Comment by andwah** [comment]
> I just want to confirm that it won't generate any problems. Could you confirm? :)

It's should be safe.

In the future i will add so it will be possible to have "tags/labels" on apps,  then they can be grouped and categories etc.

Also im thinking of renaming the "namespace" concept to just call it "ID"

**Comment by mmnosek** [comment]
I really like the idea of tags or labels.

On the renaming namespace, I would think how it looks like in "other" app stores. First things which came to my mind are mobile stores, so:
- Google Play: Package Name
- App Store: Bundle identifier
- Windows Store: Package Name.

So maybe "Package name" is the way to go? ID is also reasonable.

**Comment by andwah** [comment]
Packages is what we upload, What about `AppID` if we cant just call it `ID`

Some background:
An app can have multiple versions, versions is uploaded as packages.
To know where to apply the package when it's uploaded we look for the `Namespace`. Packaged are match by it's `Namespace `and the App `Namespace`.

Now the `Namespace` is unique per organization, maybe i will make it unique per warehouse if we are going to name it AppID or so, need to think a bit more on this.

**Comment by andwah** [comment]
I created two new  issue:

- https://github.com/Starcounter/Warehouse/issues/110 Renaming namespace
- https://github.com/Starcounter/Warehouse/issues/111 Tags & labels

**Comment by andwah** [comment]
can this be closed @mmnosek ?

**Comment by mmnosek** [comment]
Sure! Closing. We've decided to change a namespace to Starcounter.AppName together with every new app release, so it will be done consecutively. Thanks for your help and creating separate issues!
