### ISSUE TITLE
Introduce new Warehouse as default in 2.3

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Warehouse#105]
We want to switch to the new Warehouse and make people familiar with it. Now it's not easy to find the checkbox at the top for the new users. 

I think that it's reasonable to enable new Warehouse by default and also remove "beta" mark on it. WDYT? Of course there should be still possibility to use old one.

cc @andwah @warpech @dan31

**Comment by warpech** [comment]
I agree it would be great, because then we can stop maintaining apps in two Warehouses.

**Comment by andwah** [comment]
Also agree. im on parental leave until dec 5,   ill will try to fix this as soon as i get some time over.

**Comment by andwah** [comment]
I think we should remove the ability to get apps from the "old" appstore and just use the new Warehouse for `develop` and `pnext`.

**Comment by andwah** [comment]
cc @warpech  @mmnosek  @dan31

**Comment by andwah** [comment]
old app store removed, code pushed to develop

**Comment by andwah** [comment]
and now also to pnext
