### ISSUE TITLE
Get user session when user upload a file.

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#11]
When a user uploads a file it uses websocket's to to that and when an upload is finished (on server side) we do not have a reference to the user session. The user session is needed to get current user and to set permissions on created objects.

A solution is to somehow send a message from the client with the finished uploaded file, then on the server we know the session.

**Comment by alemoi** [comment]
Thank you for asking! When you get the web socket data, I suppose you have a WebSocket object, right? So the Session property of that WebSocket object, what does it contain?

**Comment by andwah** [comment]
@alemoi the Session property on the socket is null, but that is correct because in my case i establish the connection from java script on the client side using the Web Socket API. There is no option to pass any headers that we need when doing the initial request.

I think i found a solution, I will send the session "cookie" as an parameter to the URL. And on the server side i hope there is a way to find a session from the "cookie".

**Comment by alemoi** [comment]
Yes, if you send session information in the ws upgrade then you can attach session to the WebSocket upon creation. This is the standard approach.

**Comment by andwah** [comment]
@alemoi Is there a way in an app to get the right session if i have the session "cookie". ?

**Comment by alemoi** [comment]
@warpech summarized possible ways: https://github.com/Starcounter/Starcounter/issues/2713#issuecomment-103026244

There is no way to get session object from string, but you can do `Session.ScheduleTask` as described here: http://starcounter.io/guides/web/sessions/

**Comment by andwah** [comment]
@alemoi thanks for the answer, i already tried `Session.ScheduleTask` but with no success.

Can you give an example on how i can use `Session.ScheduleTask` to get hold of a specific session, i have the session id string `/__default/9DB807BE510C909E10000060`

**Comment by alemoi** [comment]
Sure. Just use this part as session string: 9DB807BE510C909E10000060 And the delegate with first Session and second String object.

**Comment by andwah** [comment]
@alemoi thanks. worked nicely

**This is how i finally solved it:**

By adding the `sessionId` as a query parameter to the URL when connecting(with `WebSockets`) i manage to pass the `sessionId` to the server, as it was not possible to set the headers on the request itself.

On the server side i kept the `sessionId` in a list when the Handler was invoked, just after the  'SendUpgrade(...)` call.

At any time i wanted to push changes to the client i recovered the kept `sessionId` and called this code snippet
```
Session.ScheduleTask(sessionId, (Session session, String sid) => {

         if( session != null && session.IsAlive() ) {
                  session.CalculatePatchAndPushOnWebSocket();
         }
});
```
