### ISSUE TITLE
The user is already an member of this organization

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#12]
When I try to add an already existing user to be a member of a store, then I see the following page:

```
Already Exists

The user is already an member of this organization
```

The message should be shown in the dialog box instead of occupying entire page. The text should also be fixed: "a_ member".

**Comment by andwah** [comment]
Fixed 82fa5fafdbd441c3df26962da22d239d78468c99

![image](https://cloud.githubusercontent.com/assets/2656996/13052649/4786d49c-d400-11e5-9fc0-f08e759901b0.png)
