### ISSUE TITLE
Add upload button on the app page

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#14]
This is how app page looks now:

![image](https://cloud.githubusercontent.com/assets/6435556/13042589/ab09cf2c-d3c1-11e5-8a6f-961846a7e6b5.png)

I have removed the only existing app version, and there no option to upload another version.

**Comment by andwah** [comment]
Duplicated, see issue #9

In this simple version of the Warehouse, application versions is uploaded from the Organization page.

**Comment by miyconst** [comment]
Yes, closing as a duplicate. Right now upload package is a separate page, we can just add a link to the page from the app details page.
