### ISSUE TITLE
Nothing happens after an app version has been uploaded

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#15]
Warehouse should redirect user to the app details page after an app was uploaded. Right now nothing happens in UI when an app version was uploaded.

If the file is small enough the upload process blink for a second and hides. Looks like nothing has happened.

**Comment by andwah** [comment]
Yes. i need some help from @miyconst  you on the javascript side,, need to capture an event from the upload element to navigate back/close current page. 

The Upload element fires an event when all uploads is done.

**Comment by miyconst** [comment]
Sure, I take this one then.

**Comment by andwah** [comment]
Resolved, After upload is finished, the result will be shown in a list with successes and failures
