### ISSUE TITLE
Rename uploads button to upload an application

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#16]
For me `UPLOADS` sounds like a page to see history of my previous uploads.

**Comment by andwah** [comment]
Yes. It will be page with "pending"  uploads, a pending upload can be an uploaded version that is not connected to an "Application" or has not been verified etc.. (this has not yet been developed). Maybe we can handle this on another page, 

Let's have a discussion on how to do this in a user friendly way.

**Comment by miyconst** [comment]
Are we going to make this page in the minimum version? Let's just rename the button for now, and later we can add a page "Upload history".

**Comment by andwah** [comment]
> Are we going to make this page in the minimum version?

No, this "pending" handling will be in the future, For now the system will auto-create an missing application for the uploaded version.

The help i need from you is how to catch the fired `done` event from `<file-websocket-upload>` element.
https://github.com/Starcounter/Warehouse/blob/master/src/wwwroot/warehouse/viewModels/UploadVersionsPage.html#L11

When the event if fired i want to navigate to the organization page.

**Comment by andwah** [comment]
The user is actually uploading a "Version" of the Application, 

Maybe "Upload Application Version"  will be more describing?

**Comment by miyconst** [comment]
`Upload Application Version` - sound good to me.

**Comment by andwah** [comment]
Resolved ff38a9a652f6118bdb66b9345110f59f7f9647d3
