### ISSUE TITLE
It is possible to upload multiple packages of same app with same version

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#17]
Warehouse should not let users create multiple same versions of an app. The solution could be:

- Automatically overwrite existing version.
- Show a message, that this version has already been uploaded.

**Comment by per-samuelsson** [comment]
> Automatically overwrite existing version.

I suggest don't. It will make it easier to produce a mistake. Better force them to delete a package explicitly first.

In general, I think we should implement the same protocol as other similar services, like NuGet, etc.

**Comment by miyconst** [comment]
@per-samuelsson I also prefer the second solution.

**Comment by andwah** [comment]
Added a check for existing versions. Duplicated versions will be rejected.

Resolved 6b0d533a902eccb5b4ae0bc934cdba30dc5a73ee
