### ISSUE TITLE
Add application/suite dialog on the Suite details page should be reset on open

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#19]
Test case:

1. Create an app suite.
2. Add an app to the suite.
3. Press `ADD APPLICATION/SUITE` button to add another app.
4. The dialog opens again.
5. The dialog input has previously entered value and the search result shows already added application.

The add application/suite dialog should reset it's values on open.

**Comment by andwah** [comment]
Popup window current data is reseted when open/closed

Fixed 21d5bbfb259c3133c019a8a2a768113c0a7a6ac3
