### ISSUE TITLE
Customer registration

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#2]
Warehouse should be able to serve new customers/users in the following way:

## Anonymous user
- Warehouse displays sign in/registration form.

## Authenticated user, but without an organization
- Warehouse displays a page which tells user that he is not a member of any organization and proposes to create a new organization.
- User fills in required fields and submits form.
- Warehouse creates new Organization, grants full permissions to the user.
- Warehouse redirects to the Organization page.

Warehouse should Hook to `Warehouse.Database.UserSession` database class and update it's status according to currently signed in user.

**Comment by andwah** [comment]
Just wanted to add that an anonymous user should also be able to learn what the "Warehouse" is etc..

**Comment by miyconst** [comment]
I think, it is not necessary for the first version, especially if take in account that users will come to there after Starcounter installation. And they will come to Starcounter installation from starcounter.io website, which would have any description required.

**Comment by andwah** [comment]
*bump*

**Comment by miyconst** [comment]
@andwah thank you for bumping this, I hope I will be able to close it this week.

**Comment by andwah** [comment]
The deadline is today.

**Comment by miyconst** [comment]
It's done. All you need is start Registration app and open `/warehouse`. If you are not signed in, then you will be prompted to sign in or register. After registration will get signed in automatically.

**Comment by andwah** [comment]
i only see this:
![image](https://cloud.githubusercontent.com/assets/2656996/13399753/1c00239a-df05-11e5-945a-223fbb44ab8a.png)

My apps:
![image](https://cloud.githubusercontent.com/assets/2656996/13399768/3513f500-df05-11e5-8bd5-b6db08551b8c.png)

**Comment by miyconst** [comment]
This is the old version.

**Comment by miyconst** [comment]
You have to checkout latest master branch of Registration app.

**Comment by andwah** [comment]
Ahh, I used the one on the appstore.
If the Registration app is "production" ready please upload it to the Appstore, this will make it easier to install the Warehouse env on the server.

**Comment by miyconst** [comment]
I will do that as soon as I have land line internet connection.

**Comment by miyconst** [comment]
Done. Version `0.0.7` uploaded.

**Comment by andwah** [comment]
When i click the `Register"` button nothing visual happends.

![image](https://cloud.githubusercontent.com/assets/2656996/13425007/722a9170-dfa4-11e5-99c5-27bd33f2ff0b.png)

In the console i get this line:

`Uncaught TypeError: Cannot read property 'network' of undefined`

**Comment by miyconst** [comment]
What version of Starcounter?

**Comment by andwah** [comment]
3-4days old i guess. not sure im building it myself. I will pull the latest SC and rebuild+test.

**Comment by andwah** [comment]
Same result, What do you think i need to update? StaticFiles?

**Comment by miyconst** [comment]
Yes, the `/sys/` folder. And check in the console `Polymer.version`, it should be `1.3.0`.

**Comment by andwah** [comment]
Ah. my `Polymer.version` was `1.1.5`

**Comment by miyconst** [comment]
Make sure you don't have `Polymer`, `puppet-client` and another Starcounter static files in any of your public directories except the installation `/sys/` folder.

**Comment by andwah** [comment]
Darn. it was the browser cache "again" :-),,  now the `REGISTER` button works as expected.

But.. when i click the `SIGN IN` i get this console error:

`Uncaught TypeError: Cannot read property 'changeState' of undefined`

**Comment by miyconst** [comment]
I know. This is due to `Polymer 1.3.0` changes. Tracked in here: https://github.com/PuppetJs/puppet-polymer-client/issues/2.

I finally close this issue :).

**Comment by andwah** [comment]
Now when i click the `Register` nothing visual happens, i have the latest /sys

**Comment by andwah** [comment]
Polymer.version "1.3.0"

**Comment by miyconst** [comment]
New Registration `0.0.8` with workarounds for Polymer `1.3.0` released and uploaded.
