### ISSUE TITLE
Split applications and suites into two blocks

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#20]
Currently both applications and suites are shown in same block called `Applications`. It is a bit misleading.

**Comment by andwah** [comment]
Wont it be simpler for the user to treat an application and a suite as the same thing?.  
I think if it's possible to merge them it's a good thing.

Maybe we can still have them in the same block but mark then differently with an icon for apps and another one for suites?

**Comment by miyconst** [comment]
Let's ask for others for opinions. For me it makes more sense to separate them into two blocks. Leave it as is for now.

>Maybe we can still have them in the same block but mark then differently with an icon for apps and another one for suites?

I like the ides.

**Comment by andwah** [comment]
Added that type name after Application/suite name.
Later we can add icons etc..
See b9cbcf10605f50ed66609ccfd89ca4a393c0c463

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13046792/46b17966-d3db-11e5-860f-f6162fcdde4f.png)

**Comment by miyconst** [comment]
Looks good.
