### ISSUE TITLE
Apply better design and style for non-editable blocks

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#21]
Blocks like `Versions` of an app, which are not editable by layout editor should provide their own css rules to look good.

![image](https://cloud.githubusercontent.com/assets/6435556/13042834/ef08d16c-d3c3-11e5-9e59-769e7ee26df5.png)

*Low priority.*

**Comment by andwah** [comment]
@miyconst Do you think i should make it editable by the layout editor?,  put each item in it's own sub-partial? Or is that even possible to have a design for items in a list?

**Comment by miyconst** [comment]
No, I think you would better add custom css rules for this particular part. If you would like to make layout editor accessible, you would have to make it be a partial.

**Comment by andwah** [comment]
Fixed,

![image](https://cloud.githubusercontent.com/assets/2656996/13249341/0605e1aa-da24-11e5-9dd4-ac7534e36d78.png)
