### ISSUE TITLE
Keep in mind IE support

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#22]
Warehouse should be one of the most used Starcounter apps. That is why we should care about IE and FF from the very beginning.

This means:

- [x] 1. Do not use `<template is="dom-repeat">` inside `<table>`. Use [juicy-table-repeat](https://github.com/juicy/juicy-table-repeat) instead. (no tables was used)
- [x] 2. Do not use `<template is="dom-repeat">` inside `<select>`. Use [juicy-select](https://github.com/juicy/juicy-select) instead, an example is available in [KitchenSink](https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/wwwroot/KitchenSink/DropdownPage.html).
- [x] 3. Do not use `document.currentScript`, use `document._currentScript || document.currentScript` instead.
- [x] 4. If possible avoid client side functions like `isEqual`, `getOrganizationHref`, do the calculations on server side.

**Comment by miyconst** [comment]
Closing this issue. All the client side was clean up.

**Comment by andwah** [comment]
Nice. now we can take this as an example and continue with WarehouseClient / PlaygroundKeeper.
