### ISSUE TITLE
Pressing enter key on a Messagebox generates an error

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#26]
If you hit the ENTER key when this window shows
![image](https://cloud.githubusercontent.com/assets/2656996/13220753/2df770a4-d978-11e5-87f1-5d99bd150fbd.png)

Browser Error:

![image](https://cloud.githubusercontent.com/assets/2656996/13220845/b1699980-d978-11e5-9203-f5a6c8f9dfb3.png)

**Comment by andwah** [comment]
The Messagebox has been replaced by the `paper-dialog`, see #51.

Verify that this works with the `paper-dialog`

**Comment by miyconst** [comment]
@andwah take this one after the demo please.

**Comment by andwah** [comment]
Cant be reproduced with the paper-dialog.
