### ISSUE TITLE
Create External API

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#31]

**Comment by miyconst** [comment]
- Warehouse user should be able to setup a password per AppStore to access it via API.
- Warehouse AppStore entry point should be a single line URL which includes all necessary information to uniquely identify AppStore.
- The AppStore entry point will be used in the AppStore application to communicate with Warehouse via API.

**Comment by andwah** [comment]
1) What do you think about using an auto generate api key for each depot instead of a password, more user friendly. no need to remember password etc.

2) the endpoint will include a query parameter with the api key.

**Comment by miyconst** [comment]
1) Totally fine. You can generate a key with `Guid.NewGuid()`.

**Comment by andwah** [comment]
The basic external REST api is in place, (using a depot key for authentication).
