### ISSUE TITLE
Navigating into Application settings page and back rises errors on console

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#33]
I just created an empty "Launcher" application. Navigating to the settings page via the cog button and back rises the errors shown below:

![image](https://cloud.githubusercontent.com/assets/6435556/13282502/9d5226fc-dae9-11e5-9d33-6703ceebc57f.png)

**Comment by andwah** [comment]
Yes i also noticed that. somehow the `SystemUser.GetCurrentSystemUser()` returns null in some cases. no sure why yet..

**Comment by miyconst** [comment]
Could you please provide some more details on this?

The value might be null if the request came without auth cookie.

**Comment by andwah** [comment]
@miyconst At the moment i do not have any more input. if i find some ill will post it here.

**Comment by andwah** [comment]
This has been fixed by @miyconst ,  the issue was the binding to the `<img>` `src` property, The correct binding is bound to the `src$` property
