### ISSUE TITLE
I am able to upload files with any type

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#34]
Whatever file I select to upload as an application version is accepted and uploaded to server.
There should be some client side validations to pass through only `.zip` files.

@andwah assign this issue on me, if it will take much time for you.

**Comment by andwah** [comment]
@miyconst  Do you get this after the upload:

![image](https://cloud.githubusercontent.com/assets/2656996/13282940/ad67b4b0-daeb-11e5-8e80-bcec5f7cf32b.png)

if so then we only need to
1. add a check in the `file-websocket-upload` element to accept `zip` files
2. add filter in the popup dialog to only show zip files.

**Comment by miyconst** [comment]
Still able to upload wrong file after disabling the filter in select file dialog.

**Comment by andwah** [comment]
> Still able to upload wrong file after disabling the filter in select file dialog.

Shit in shit out :-)

sure, we should still add some content check on the client side as well.

**Comment by miyconst** [comment]
@andwah take this one after the demo please.

**Comment by andwah** [comment]
Resolved a8a563168a5e4b9b94c084477be9d29af3933187

Now checking the mimetype of the file (delivered by browser).  Default acceptable mime types are 
`application/x-zip-compressed` and `application/zip`

We can do a byte check also but that requires a lot of more work,  and i think this is good enough for a client side validation, There is already a Server side check.

**Comment by miyconst** [comment]
Nice! This validation is enough. Closing the issue.
