### ISSUE TITLE
Implement "Private" handling on an Application Suite

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#36]
The application suite will be `private` if one or more containing applications/suites is private, otherwise it will use the application suite private flag settings.

**Comment by miyconst** [comment]
I don't think this value should be dependent on the apps.

Vendors might want to sell private apps only together in a bundle, but not separately.
Also suits for testing or development can be marked as private.

**Comment by andwah** [comment]
This is how i was thinking..

The private flag only forbids apps to be added to stores outside it's organization.
All apps in an organization (private or public) can be added to stores inside the same organization.

**Comment by miyconst** [comment]
That's correct.

But this does not say that a flag for an app suite should be readonly and determined by the apps in the store.

**Comment by andwah** [comment]
The private flag has nothing todo if an app is in a store or not. it's about if other organizations can see it or not.

If an suite has one or more private apps, that suite should not be public to other organizations.

**Comment by miyconst** [comment]
Why not?

Let's say I have developed Products and Images app. I don't sell them as an app, but only as a suite: Products with Images.

**Comment by miyconst** [comment]
@andwah can we close this issue as invalid?

**Comment by andwah** [comment]
For now the `private flag` is not dependent on the suite content.

Closing.
