### ISSUE TITLE
Implement dependencies on applications.

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#37]
Added starcounter dependency on application.

**Comment by miyconst** [comment]
You mean what Starcounter version is required to run the app? Or which apps depend on other apps?

**Comment by andwah** [comment]
@miyconst The Starcounter version the app works with.     

how we should handle what apps is needed for a fully functional app is another thing.

**Comment by miyconst** [comment]
Agree.

**Comment by andwah** [comment]
maybe we should call it `compatible` instead of `dependency.`

**Comment by miyconst** [comment]
Or `requires`, `dependency` has so many meanings, easy to get confused.

**Comment by miyconst** [comment]
@andwah I think this one can be closed, right?
