### ISSUE TITLE
Redundant padding

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#39]
This blank space looks like there is something missing.
Could you remove it?

![image](https://cloud.githubusercontent.com/assets/6435556/13323069/fb21a980-dbd7-11e5-8ec8-1fd1617ad271.png)

**Comment by andwah** [comment]
Not really, it's a twitter boostrap style called `well`

and it's supposed to be `centered`

**Comment by andwah** [comment]
Let's first decide on our overall gui/theme before we change paddings and margins.

**Comment by miyconst** [comment]
Okay, leave it for now.

**Comment by miyconst** [comment]
I have fixed styles to make it look like this:

![image](https://cloud.githubusercontent.com/assets/6435556/13425970/c3f9b840-dfaa-11e5-9248-efe527ece783.png)
