### ISSUE TITLE
Huge misleading icon on app details page

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#40]
![image](https://cloud.githubusercontent.com/assets/6435556/13323182/7e32a98c-dbd8-11e5-8ef3-ce85337ac585.png)

What the `icons` section meant to be? What this huge icon is there for?

**Comment by andwah** [comment]
> What the icons section meant to be?

Show the icons associated to the app. and the place to change it., we can remove it. it was just convenient todo as it works same with `banners` and `screenshots`


> What this huge icon is there for?

so the user can see it :-) ,,  i did not resize it as we decided not to bother with gui stuff in this beta version.

**Comment by miyconst** [comment]
Can you please just hide or remove it, as it is not yet working.

**Comment by andwah** [comment]
Well it's working, but i can change the size to a more readable format :-)

**Comment by miyconst** [comment]
How do I change the icon?

**Comment by andwah** [comment]
@miyconst In the package.zip that you upload.

**Comment by andwah** [comment]
We should use the filedrop element or similar

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13323762/2c82c4c0-dbdb-11e5-9554-0707b1259618.png)

**Comment by miyconst** [comment]
Can you hide it till we have nice UI for it? It is misleading now. If the icon will be changed, it will be visible in the small icon left to the app name.

**Comment by miyconst** [comment]
Don't remove it though.

**Comment by andwah** [comment]
i agree. the icon should only be in one place.
