### ISSUE TITLE
Version namespace do not match application namespace

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#41]
I am trying to upload an app version and getting this error:

```
Version namespace do not match application namespace
```

It should be:

- [x] Version namespace **does** not ...
- [x] Show what is the current app namespace and what is in the `zip` file.
- [ ] If application namespace is not specified in the settings, it should be automatically picked up from the uploaded file, and should not show the error.

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13428266/c009d508-dfb9-11e5-8bb3-d0b9827b1b63.png)

**Comment by miyconst** [comment]
Looks good.

**Comment by andwah** [comment]
@miyconst I only fixed the first thing of three in the list.

**Comment by miyconst** [comment]
Sorry, wrong button.

**Comment by andwah** [comment]
> If application namespace is not specified in the settings, it should be automatically picked up from the uploaded file, and should not show the error.

This is not possible, the namespace has to be entered to be able to create an application. Blank namespaces should not be possible.
