### ISSUE TITLE
The back button has strange behavior

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#43]
- Open an app details.
- Open the app settings page.
- Press back button - goes to app details page.
- Press back button - goes to app settings page.
- Press back button - goes to app details page.

The back button should always return to one specific page, regardless of where user was before.

cc @warpech, @Starcounter-Jack

**Comment by andwah** [comment]
yes. i know of this. 
we need to have some better check on where the user really want to go when the `back` button is pressed

**Comment by andwah** [comment]
Back button has been removed, see #61
