### ISSUE TITLE
Create a BaseClass for all database classes

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#47]
All database classes should inherit base class:

```cs
[Database]
public class BaseClass {
    public string Key { get { return this.GetObjectID(); } }
    public DateTime ChangeDate { get; set; }
    public DateTime CreateDate { get; set; }
    public string Creator { get; set; } //Username of currently signed in user who created the object
    public string Changer { get; set; } // Username of currently signed in user who made the change
}
```

Each class needs Hooks to update the values.

**Comment by andwah** [comment]
I think it can be good to have a "ChangeDate" on some classes, but not all of them.
And if we want to keep track of user actions it should be done in a own class (table).

**Comment by miyconst** [comment]
It's always nice to have a base class for all db classes.

Why do you think we don't need those properties for all classes? It would be good to have them, but if it takes too much time to implement, than it does not worth it.

**Comment by andwah** [comment]
> Why do you think we don't need those properties for all classes?

 At the moment we only need one property `ChangeDate` in one class.

I think we can implement the base class when it's needed a bit more.

**Comment by miyconst** [comment]
Okay, let's keep it like this for now.

**Comment by miyconst** [comment]
Close this issue to avoid issue-lepsy.
