### ISSUE TITLE
Warehouse architecture and solutions

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#48]
After today's discussion with @Starcounter-Jack I have added two more GitBook pages to describe architecture of Warehouse + WarehouseClient and the solutions we should provide.

https://starcounter.gitbooks.io/rebelslounge/content/warehouse/warehouse_architecture.html
https://starcounter.gitbooks.io/rebelslounge/content/warehouse/warehouse_solutions.html

@andwah please read and confirm or deny that this is same thing we were talking before.
@Starcounter-Jack could please also find five minutes to read the pages and confirm that I am right.

As usual, any comments and feedback are welcome.

**Comment by andwah** [comment]
Question about the "warehouse_architecture.html",:
What is the usage of the Rest API between the `Warehouse `and `Starcounter hosting`?

**Comment by miyconst** [comment]
There will be PlayGroundKeeper installed on the Hosting machine. Warehouse will install the apps in there using PlayGroundKeeper.

**Comment by andwah** [comment]
Okey,, so it will be the standard warehouse api for retriving apps. (same api the the Warehouse client will use).

As i understand it, the `Playgroundkeeper `will NOT run on the `Starcounter hosting` machine, it will run on the client machine where `Warehouse Client `is running. The `Starcounter hosting` is where we have a lot of databases that run the client (bought) apps.

**Comment by andwah** [comment]
A Quick drawing:

![image](https://cloud.githubusercontent.com/assets/2656996/13608299/748db25c-e554-11e5-90df-478ed2dcbdc1.png)

**Comment by andwah** [comment]
Current plan is to remove the `Playground Keeper` from `Client Machine` and take the needed bits from it and implement those in the `Warehouse` app.

`Warehouse Client` will make the command (Point 2 in the image) to the `Warehouse `and it will relay that command to the `Hive` (Easy explained).

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13667290/e9c6f7ec-e6b5-11e5-9cb3-fb0ee8f4577d.png)

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13727762/415fc1fe-e900-11e5-9406-ffe546de096b.png)

**Comment by andwah** [comment]
![image](https://cloud.githubusercontent.com/assets/2656996/13727773/873c13ee-e900-11e5-8705-eb4416b50112.png)

**Comment by miyconst** [comment]
@andwah do you have this diagram in svg?

**Comment by andwah** [comment]
yes in `dropbox/exchange/<my folder>/Warehouse/Warehouse-Client-Hive.svg`

**Comment by miyconst** [comment]
Thank you, the GitBook page is updated.

**Comment by miyconst** [comment]
Closing this issue as we both agreed on same solution.

**Comment by andwah** [comment]
Current database model

![image](https://cloud.githubusercontent.com/assets/2656996/14172355/f2d5b8fe-f737-11e5-9022-9f3375b6edbb.png)
