### ISSUE TITLE
Uploading version to an application always adds a new icon and a banner

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#49]
![image](https://cloud.githubusercontent.com/assets/6435556/13815372/98cbae44-eb8a-11e5-8cd5-728fa0c352a2.png)

I have uploaded and removed the same version three times, in the result I see three same icons and three same banners.

**Comment by andwah** [comment]
Fixed: f7d8fbc749234b9b1dde90042c3b54e73f356134
