### ISSUE TITLE
Replace all history.backI() with a static url

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#61]

**Comment by andwah** [comment]
the `history.back()` can not be replaced with a static url, it's dynamic. it depends on where the user was before.

**Comment by andwah** [comment]
Why not remove the back button everywhere, i think we can manage without it. and as you say it also confuses the user (two back buttons that not always do the same thing).. 

Let's remove it, do you agree?

**Comment by miyconst** [comment]
Okay, let's remove the button, we can navigate with the breadcrumb.

**Comment by andwah** [comment]
Nice.. i will remove it.

**Comment by andwah** [comment]
Backbuttons removed, 58f7257d6d9a447e46f00130b5f45c7f2debca4d
