### ISSUE TITLE
Organization member page does not show any information about the organization

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#62]
Organization members page is located here:
http://localhost:8080/warehouse/organizations/miyconst/members

But the a single member page does not show any info about the organization it belongs:
http://localhost:8080/warehouse/members/o

**Comment by andwah** [comment]
What kind of information do you want to show on the a member page?  

* List all all organizations that the member is member of
* List all all stores that the member is member of

**Comment by miyconst** [comment]
I thought the page shows details of "organization-member", not all details of this user.

Do you think we should show full user details for everyone who added the user as an organization member?

I think it should only show details of the user per organization.

**Comment by andwah** [comment]
An `organization member` is a user that is a member of an organization or a store.

We should maybe rename the handler url from `http://localhost:8080/warehouse/members/o` to `http://localhost:8080/warehouse/users/o`

A member page in warehouse is similar to a user in github, take a look at https://github.com/miyconst for example.



> Do you think we should show full user details for everyone who added the user as an organization member?

Well.. only information that the user give permission to, for example a checkbox if they want the email to be public etc...

**Comment by miyconst** [comment]
Hm, then I misunderstood the meaning of the page.

I am not sure we should share all the user details with everyone. Should we?

**Comment by andwah** [comment]
> I am not sure we should share all the user details with everyone. Should we?

We do it in a similar way github does it.

**Comment by miyconst** [comment]
Okay, let's leave it as is for now.
