### ISSUE TITLE
App from an organization is available another one

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#63]
I have an organization `Miyconst` under user `admin`. There is an app `Launcher` uploaded by `admin` into `Miyconst`.

Then I register another user `mm`, and create a new organization `mm`. In the organization create a new app, name it `Launcher`. When I open the app details it shows me information about the `Launcher` created by `admin` and uploaded to `Miyconst`.

**Comment by miyconst** [comment]
@andwah move your attention to this issue after the demo.

**Comment by andwah** [comment]
I could not recreate this, Can you be more specific on how to recreate? (maybe this has been fixed during other fixes?)

**Comment by miyconst** [comment]
Yes. I think it was fixed, can't reproduce it either. Closing the issue for now.
