### ISSUE TITLE
A workspace without AppName....

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#64]
Running the Latest `Launcher` v3.1.6 and the `Warehouse` from the latest source.

Getting this result when navigating to `http://localhost:8081/warehouse`

![image](https://cloud.githubusercontent.com/assets/2656996/14316647/83eb6fc0-fc04-11e5-8e16-151919e25cec.png)

**Comment by miyconst** [comment]
Are you running Launcher from GitHub or install from AppWarehouse?

**Comment by andwah** [comment]
> Running the Latest Launcher v3.1.6 and the Warehouse from the latest source.

From AppWarehouse, if that is not the correct version please upload the correct version to the AppWarehouse.

**Comment by miyconst** [comment]
Launcher `3.1.7` released.

**Comment by warpech** [comment]
> Launcher 3.1.7 released.

Thank you @miyconst. I just think that the number of changes would justify increasing the major number, or at least the minor. It is certainly not just a patch to 3.1.6 ;)

**Comment by miyconst** [comment]
Agree. Short after the `3.1.7` @tomalec updated `juicy-tile-editor`. So, I am going to release `4.0.0`.

**Comment by miyconst** [comment]
@warpech, @tomalec could you please write release notes for the Launcher `4.0.0`?

**Comment by warpech** [comment]
Sure, I will: https://github.com/StarcounterPrefabs/Launcher/issues/221
