### ISSUE TITLE
Fix Sign-in / Registration window

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#65]
This is how it looks today if you are an anonymouse user
![image](https://cloud.githubusercontent.com/assets/2656996/14345564/df34415a-fcad-11e5-8e67-b7a54d01fe26.png)

**The login screen should have this info***

	Username:______
	Password:______
	[x] Keep me signed in
	[Sign in]
	[Dont't haven an account? Sign up]
	[Forgot password]

Later more sign in options will be added, (github,googl,facebook,twitter sign in etc..)

**Comment by miyconst** [comment]
The new sign in app provides both registration and sign in forms.
