### ISSUE TITLE
Create a WarehouseLauncher

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#67]
The warehouse Launcher will have a topbar with some logo and the sign-in icon at the right corner. And if the user is sign-in as "Administrator" also an Settings `/warehouse/settings` icon will be there.

**Comment by miyconst** [comment]
Removing my assignment, since I do not have time for it.

**Comment by andwah** [comment]
@miyconst Can you recommend anyone else that can take over it?

**Comment by miyconst** [comment]
Unfortunately we do not have resources for it currently. So, the only option is to keep using our current Launcher. 

And later it will be developed by me or someone else.

**Comment by andwah** [comment]
Why do we need 'a' launcher?  i can just map the sign-in stuff into the Warehouse app. or what am i missing?

**Comment by miyconst** [comment]
You are missing nothing. Just it looks better in a Launcher :)

**Comment by andwah** [comment]
Obsolete , Warehouse does not need an Launcher it's a "standalone" app.
