### ISSUE TITLE
Partials overlapps

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#68]
Click `Create an Organization`
![image](https://cloud.githubusercontent.com/assets/2656996/14346012/74219d42-fcb0-11e5-9cdc-5d182b73ef33.png)

Click browser back button
![image](https://cloud.githubusercontent.com/assets/2656996/14346036/8dee27fe-fcb0-11e5-990a-e0e4567bb619.png)

**Comment by miyconst** [comment]
@andwah can you refresh page and see if the layout stays broken? If no, then this is the following issue: https://github.com/StarcounterPrefabs/Launcher/issues/181

**Comment by miyconst** [comment]
@andwah any update on this? Is it still happens?

**Comment by andwah** [comment]
I have note seen this behaviour for a long time now.

**Comment by miyconst** [comment]
Good. Closing the issue.
