### ISSUE TITLE
Create user message dialog with buttons like (yes/No)

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#7]
We will need a user message dialog with button options.

First use will be when deleting organizations and stores.

Example:
![imgres](https://cloud.githubusercontent.com/assets/2656996/12812954/51503a46-cb35-11e5-8379-ea98e8d30826.jpg)

**Comment by miyconst** [comment]
I have already created such thing in our sample apps. Take a look at the Barcodes application: [HTML](https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/wwwroot/Barcodes/viewmodels/BarcodesPage.html#L48), [JSON](https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/ViewModels/BarcodesPage.json#L15), [c#](https://github.com/StarcounterSamples/Barcodes/blob/master/src/Barcodes/ViewModels/BarcodesPage.json.cs#L56).

**Comment by andwah** [comment]
Did not manage to get the paper-dialog working 100%,,  so for the moment we keep the "custom" made messagebox that was pushed,  The GUI needs some work thou see separate issue #23
