### ISSUE TITLE
Mixed case in directory names

### ISSUE THREAD

**Issue by warpech** [Starcounter/Warehouse#72]
The source code contains the following subdirectories in https://github.com/Starcounter/Warehouse/tree/master/src/wwwroot:

- `Warehouse` (uppercase W)
- `warehouse` (lowercase w)

This may turn to be a problem at some point

**Comment by miyconst** [comment]
@warpech thank you, fixed.
@andwah please follow the [Project Structure](https://starcounter.gitbooks.io/guidelines/content/project_structure.html) guide next time.
