### ISSUE TITLE
Auto close (with timeout) successfully notices

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#77]
![image](https://cloud.githubusercontent.com/assets/2656996/15107310/5d1fd8ec-15cf-11e6-9cad-5a8ba33f4a78.png)

**Comment by miyconst** [comment]
Fixed, now the `notices-panel` has a new property `timeout` which indicates for how long a notice will be shown, in seconds, default value is `10`.

**Comment by andwah** [comment]
The auto-close works fine, but it closes all type's (Info,Success,Warning,Danger) notices.

I thought it would be nice only to close `Info` and `Success `types and leave the rest up to the user to close.  What do you think?

**Comment by miyconst** [comment]
Agree. How do I get the item of a notice?

**Comment by andwah** [comment]
In the `notices-panel` element there is a property `type`
```
 Info = 0,
 Success = 1,
 Warning = 2,
 Danger = 3,
```

**Comment by miyconst** [comment]
Done. Hide only `Type < 2` items, https://github.com/Starcounter/Warehouse/commit/6a61220fc93031e4171fc563332f3f70c69494e0.
