### ISSUE TITLE
Can not sign in when Notice is visible.

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#79]
When a "Green" Notice is visible the sign out popup is closed before i have time to click the sign out button.

![image](https://cloud.githubusercontent.com/assets/2656996/15140325/dd8566b6-169a-11e6-953a-a3ffb7cd2a9f.png)

Maybe the "timer" thing in Notice auto-close is doing something?

**Comment by miyconst** [comment]
Could you please provide full screen picture?

Does it happen only when the notice being closed or any time?
Seems I know the reason, will do a partial fix.

**Comment by miyconst** [comment]
The reason was that `notice-panel` generates a click event to force dirty checking of the model and send patches to the server.

Now this will happen only when an notice was actually closed. Nothing I can do about it, sadly.

Thanks for reporting.
