### ISSUE TITLE
Naming: Software vs Application, Store vs Hive....

### ISSUE THREAD

**Issue by andwah** [Starcounter/Warehouse#8]
What should we call things?

- **Starcounter Application**
Software
Application
App
..

- **Starcounter Application Suite**
Application Suite
App Suite
Suite Software
..

- **The Place Where you can buy Starcounter Applications**
App Store
Store
Depot
Hive
..

- **The place where a vendor can host starcounter applications**
Hive, aka "Starcounter Hive"

**Comment by miyconst** [comment]
@andwah the words `Software` and `App` are on the different level.

`Software` is a base class for `App` and `Suite`.

**Comment by warpech** [comment]
Please make sure this vocabulary is explained in GitBook once you decide on it

**Comment by miyconst** [comment]
@andwah, @Starcounter-Jack 

Here is what I think. Database class name and UI name should not be the same.

**The database class name should be**:

- As short as possible.
- Unique in the scope of application.
- Do not use same names from Simplified or SocietyObjects for different classes.
- Understandable for developer.

**The UI name should be**:

- Understandable for end users which are not familiar with our concepts.
- Use natural language.
- Do not care about database class names.
- Do not invent new name if there is an existing one.

That is why I prefer the following naming:

- **Vendible item in Warehouse**
DB - `Software`.
UI - Not available.

- **Starcounter Application**
DB - `App`.
UI - Application.

- **Starcounter Application Suite**
DB - `Suite`.
UI - Applications suite.

- **The Place Where you can buy Starcounter Applications**
DB - `Depot`. The `Store` is a better name, but it has different meaning in SO, that is why I tend to `Depot`.
UI - Applications store.

- **The place where a vendor can host starcounter applications**
DB - `Hive`. The `Host` could be a better name, but it has very wide range of meanings. That is why I tend to `Hive`.
UI - Applications hosting. Can be "Shared" or "Private".

**Comment by andwah** [comment]
@miyconst Thanks. i will make the necessary adjustments to the code.

btw, Imagine in the future that the warehouse also can have other things than software items, maybe some vendor also want to sell some kind "Support/hosting" for a the Application Suite.

**Comment by miyconst** [comment]
Hm, this is the question to @Starcounter-Jack. Initially I called `Software` as `Item`, so we can add any kind of vendible objects to the database, but the name was rejected by @Starcounter-Jack.

**Comment by andwah** [comment]
> Do not use same names from Simplified or SocietyObjects for different classes.

Why not?.. An app developer do not care about Simplified, SocietyObjects  he should be able to call the class whatever he likes right?

Some alternatives for `Software` maybe?

- Vendible
- Product

**Comment by miyconst** [comment]
>SocietyObjects he should be able to call the class whatever he likes right?

Yes, but because of mapping issues we have to keep our database Simplified/SocietyObjects aware, to simplify the mapping process.

**Comment by miyconst** [comment]
It looks like there are no any objections about the naming I proposed. I have moved the description to the GitBook: https://dan31.gitbooks.io/rebelslounge/content/warehouse/warehouse_terms.html.

Closing the issue.

**Comment by andwah** [comment]
Tree = Host
Hive = Database 
Bee = The Apps

**Comment by Starcounter-Jack** [comment]
Thank for the ideas.

The modern word for Application is App. This marks the move to less monolithic applications and is know widely beeing adopted in enterprise software.

We want to reserve the word database to mean the datastore accessible using SQL and DML. These stores are virtualised. This is why we introduce Hive as the data boundary spanning multiple databases.

**Comment by Starcounter-Jack** [comment]
# Summary

1. Applications are called Apps.
2. Application and SQL accessible data stores are called Databases (or Virtual Databases).
3. Databases are mapped onto a Hive. A Hive can host multiple databases. Databases can map to the same location in a Hive.
4. Host is called Host
5. The repository of Starcounter Apps available for reselling or free use is called the App Warehouse.

**Comment by miyconst** [comment]
>Databases are mapped onto a Hive.

What means mapped database?

**Comment by miyconst** [comment]
>The modern word for Application is App.

This sounds good for me, and does not require much change, only UI title.

>Application and SQL accessible data stores are called Databases (or Virtual Databases).

This would be very difficult to explain to someone who is familiar with MS-SQL, MySql or any NoSQL databases.

Closing this issue as inactive. Another discussion should take a place if we want to change the naming again.

@Starcounter-Jack please do not open this issue, if you want to add/change/discuss something, let's do that face to face.
