### ISSUE TITLE
Some minor spelling errors

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Warehouse#80]
[OrganizationHostingPage.html](https://github.com/Starcounter/Warehouse/blob/d00652c42b962482b3a91003da065f65caf3fbbe/src/wwwroot/Warehouse/viewmodels/OrganizationHostingPage.html): 

- change _distirbute_ to _distribute_
- first pullet point is not ending with a period, all the others are: _Click on the Warehouse client link_**.**
- change _appication_ to _application_
- change _untill installaction_ to _until installation_

**Comment by miyconst** [comment]
Thank you @ubbeK, fixed now.
