### ISSUE TITLE
Setup Selenium tests

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Warehouse#89]
First, need a basic set of tests:

- App starts.
- Page opens.
- Able to sign in.

@ubbeK can you do that?

**Comment by ubbeK** [comment]
@miyconst: Sure

**Comment by miyconst** [comment]
Take this is a lower priority compare to MM.

**Comment by ubbeK** [comment]
Could you please assign it to me, I dont have that option.

**Comment by miyconst** [comment]
Assigned, also granted you write permissions to the repository.

**Comment by miyconst** [comment]
The test project has been set up. There are also two basic tests. Closing this issue. Actual tests should be tracked in separate issues.
