### ISSUE TITLE
Replace juicy-style with template is="starcounter-composition"

### ISSUE THREAD

**Issue by warpech** [Starcounter/Warehouse#93]
This task is the part of the effort to implement https://starcounter.gitbooks.io/rebelslounge/content/app/client/layouts/longterm_solution_md.html

Support for `juicy-style` is being removed from Launcher, starting from Launcher `develop` branch.

Use Products app as reference for this task (https://github.com/StarcounterSamples/Products/issues/18)

---

In the Warehouse app, replace `juicy-style` with `template is="starcounter-composition"`.

Do this on Warehouse `develop` branch, which can be merged to Warehouse `master` branch after Starcounter stable is aware of `template is="starcounter-composition"` (see [branching policy](https://starcounter.gitbooks.io/guidelines/content/branching.html))

**Comment by andwah** [comment]
Removed deprecated juicy-style tag.  

No need for creating a `develop` branch. We are not using `starcounter-composition` at the moment.
